### ISSUE TITLE
Missing UXTD prompts

### ISSUE THREAD

**Issue by carmocca** [UltraSuite/ultrasuite-doc#2]
Hi,

I was checking the number of prompts in the UXTD dataset and got a total of 4609. This does not seem to match the 4619 indicated in Table 2 of the paper (also in https://github.com/UltraSuite/ultrasuite-doc/blob/master/docs/data/data.md) and the counts displayed in `core-uxtd/doc/prompts`.

Looking at the difference, the following prompts seem to be missing:

| Prompt                                       | Count |
|----------------------------------------------|:-----:|
| close-back-rounded-vowel teaching no-context |   2   |
| alveolar                                     |   1   |
| close-back-rounded-vowel teaching dV         |   1   |
| l ala eelee ol                               |   1   |
| lateral                                      |   1   |
| p apa eepee opo                              |   1   |
| palatal-stop teaching no-context             |   1   |
| retroflex-fricative teaching no-context      |   1   |
| spread-lips-post-alveolar-fricative          |   1   |

For reference, I used the following code to check it:
```python3
import pandas as pd
import pathlib
from ustools.read_core_files import parse_prompt_file
from collections import Counter

dataset_path = pathlib.Path("UltraSuite/core-uxtd")

speakers_csv = pd.read_csv(dataset_path / "doc/speakers", sep="\t")
speaker_ids = [row[2] for row in speakers_csv.itertuples()]

prompts_csv = pd.read_csv(dataset_path / "doc/prompts", sep="\t", usecols=[0, 3])
prompt_csv_counter = Counter({p: c for p, c in prompts_csv.itertuples(index=False)})
# Check that the counter creation is correct
assert sum(prompt_csv_counter.values()) == sum(prompts_csv["Count"])

counter = Counter()
for speaker_id in speaker_ids:
    speaker_path = pathlib.Path(f"{dataset_path}/core/{speaker_id}")
    session_ids = set(f.stem for f in speaker_path.glob("*"))
    for session_id in session_ids:
        session_path = speaker_path / session_id
        prompt, _ = parse_prompt_file(session_path.with_suffix(".txt"))
        counter.update([prompt])

print(prompt_csv_counter - counter)
print(sum(counter.values())) # 4609
```

If my code is correct, you might want to double check the original prompt counts or look for the missing files.

cc: @aeshky 

Thank you.

**Comment by msamribeiro** [comment]
Thanks for spotting this!

We may consider the details of the paper as version 0.1 of the repository, which we never made public.
The first public release is version 1.0 and we took care to remove identifiable information and discard unusable utterances (poor recording or corrupted data). So some numbers might change with respect to version 0.1. See [here](https://ultrasuite.github.io/faq/#why-is-there-a-difference-in-the-numbers-reported-here-and-those-in-the-paper).

For the public release, we should've updated the doc/prompts with the new counts, but somehow that was forgotten. Thanks for finding it! I have now updated the prompt count to match version 1.0 and I've included a changelog in uxtd/doc to log these changes.

**Comment by carmocca** [comment]
You might want to also update the counts for uxssd and upx. I noticed later that the counts are also incorrect.

**Comment by msamribeiro** [comment]
Thanks, this is now fixed. I found upx to be correct, but I have updated uxssd. Let me know if you find additional issues.

**Comment by carmocca** [comment]
Thank you for your quick fixes! Just noticed a few more issues.

In the prompts file for uxssd, "swallow" (type non-speech) has no code assigned, instead it's marked as "#N/A"

Also, I noticed a weird notation for the following prompts:
```
core-uxssd/core/08M/Therapy_05/001F.txt:tk_-2SD
core-uxssd/core/08M/Therapy_05/002F.txt:tk_-1SD
core-uxssd/core/08M/Therapy_05/003F.txt:tk_mean
core-uxssd/core/08M/Therapy_05/004F.txt:tk_+1SD
core-uxssd/core/08M/Therapy_05/005F.txt:tk_+1SD
core-uxssd/core/08M/Therapy_05/006F.txt:tk_+2SD
core-uxssd/core/08M/Therapy_05/007F.txt:ptk_-2SD
core-uxssd/core/08M/Therapy_05/008F.txt:ptk_-2SD
core-uxssd/core/08M/Therapy_05/009F.txt:ptk_-1SD
core-uxssd/core/08M/Therapy_05/010F.txt:ptk_mean
core-uxssd/core/08M/Therapy_05/011F.txt:ptk_+1SD
core-uxssd/core/08M/Therapy_05/012F.txt:ptk_+2SD
core-uxssd/core/08M/Therapy_05/013F.txt:ptk_+2SD
```
Listening to the respective audio files the child does say `tk` and `ptk` in the audio, however, I don't get why are the prompts labelled as "mean" or "standard deviation".

Thank you for your help.

**Comment by aeshky** [comment]
Hello,

The prompt files containing means and standard deviations are part of the Diadochokinesis imitation task which we mention briefly in [1]. The SLT plays a recording of a phone at different speeds, and the child is expected to imitate what they hear. The means and SDs refer to how the speed is calculated. Please see [2] for more information. 

Thanks!
Aciel 

[1] A. Eshky, M. S. Ribeiro, J. Cleland, K. Richmond, Z. Roxburgh,J. M. Scobbie, and A. A. Wrench, “Ultrasuite: a repository of ul-trasound and acoustic data from child speech therapy sessions,” in19th Annual Conference of the International Speech Communica-tion Association (Interspeech), 2018, pp. 1888–1892.

[2] J. Cleland, J. M. Scobbie, and A. A. Wrench, “Using ultrasoundvisual biofeedback to treat persistent primary speech sound disorders,”Clinical Linguistics and Phonetics, vol. 29, no. 8-10, pp.575–597, 2015.
